feat(docker): cleanup and unify docker files (clang, target, flags)

diff --git a/crates/iota-rosetta/docker/iota-rosetta-devnet/Dockerfile b/crates/iota-rosetta/docker/iota-rosetta-devnet/Dockerfile
--- a/crates/iota-rosetta/docker/iota-rosetta-devnet/Dockerfile
+++ b/crates/iota-rosetta/docker/iota-rosetta-devnet/Dockerfile
@@ -1,33 +1,68 @@
-FROM ubuntu:latest AS chef
-WORKDIR iota
+# Build image (the specific rust version can also be passed, e.g. "1.82-bookworm")
+ARG RUST_IMAGE_VERSION=bookworm
+FROM rust:${RUST_IMAGE_VERSION} AS builder
+
+ARG PROFILE=release
+ARG CARGO_BUILD_FEATURES
+# The GIT_REVISION environment variable is used during build time inside the rust crates
 ARG GIT_REVISION
 ENV GIT_REVISION=$GIT_REVISION
-RUN apt-get update && apt-get install -y build-essential libssl-dev pkg-config curl cmake clang git ca-certificates
-RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
-ENV PATH="/root/.cargo/bin:${PATH}"
 
-FROM chef AS builder
+WORKDIR "/iota"
 
+# Install build dependencies, including clang and lld for faster linking
+RUN apt update && apt install -y cmake clang lld git
+
+# Configure Rust to use clang and lld as the linker
+RUN mkdir -p ~/.cargo && \
+    echo -e "[target.x86_64-unknown-linux-gnu]\nlinker = \"clang\"\nrustflags = [\"-C\", \"link-arg=-fuse-ld=lld\"]" > ~/.cargo/config.toml
+
+# Install additional dependencies
+RUN apt install -y libpq5 libpq-dev ca-certificates
+
+# Clone the repository and checkout the devnet branch
 RUN git clone https://github.com/iotaledger/iota .
 RUN git checkout devnet
 
+RUN cargo build --profile ${PROFILE} \
+  --bin iota \
+  --bin iota-rosetta \
+  --features ${CARGO_BUILD_FEATURES:=default}
+
+# Copy the built binary to the working directory depending on the output folder of the profile,
+# so we can copy it to the runtime image
+RUN if [ -d target/release ]; then \
+  TARGET_DIR="target/release"; \
+elif [ -d target/debug ]; then \
+  TARGET_DIR="target/debug"; \
+else \
+  echo "Error: No build directory found"; \
+  exit 1; \
+fi && \
+mv $TARGET_DIR/iota ./ && \
+mv $TARGET_DIR/iota-rosetta ./;
+
+# Production image
+FROM debian:bookworm-slim AS runtime
+
+ARG WORKDIR="/iota"
+WORKDIR "$WORKDIR"
+
+# Install runtime dependencies and tools
+RUN apt update && apt install -y libpq5 ca-certificates curl
+
+# Install rosetta-cli
 RUN curl -sSfL https://raw.githubusercontent.com/coinbase/rosetta-cli/master/scripts/install.sh | sh -s
-RUN curl -fLJO https://github.com/iotaledger/iota-genesis/raw/main/devnet/genesis.blob
 
-RUN cargo build --release --bin iota --bin iota-rosetta --bin iota-node
+# Download the genesis file and create the genesis state
+RUN mkdir -p devnet && curl -fL -o devnet/genesis.blob https://github.com/iotaledger/iota-genesis/raw/main/devnet/genesis.blob
 
-# Production Image
-FROM ubuntu:latest AS runtime
-WORKDIR iota
-RUN apt-get update && apt-get install -y ca-certificates
-COPY --from=builder /iota/target/release/iota /usr/local/bin
-COPY --from=builder /iota/target/release/iota-node /usr/local/bin
-COPY --from=builder /iota/target/release/iota-rosetta /usr/local/bin
-COPY --from=builder /iota/bin/rosetta-cli /usr/local/bin
+COPY --from=builder /iota/iota /usr/local/bin
+COPY --from=builder /iota/iota-rosetta /usr/local/bin
 COPY --from=builder /iota/crates/iota-config/data/fullnode-template.yaml /iota/devnet/fullnode.yaml
-COPY --from=builder /iota/genesis.blob /iota/devnet/genesis.blob
 RUN /usr/local/bin/iota genesis
 
 ARG BUILD_DATE
+ARG GIT_REVISION
 LABEL build-date=$BUILD_DATE
 LABEL git-revision=$GIT_REVISION
diff --git a/docker/iota-node/Dockerfile b/docker/iota-node/Dockerfile
--- a/docker/iota-node/Dockerfile
+++ b/docker/iota-node/Dockerfile
@@ -1,40 +1,60 @@
-# Build application
-#
-# Copy in all crates, Cargo.toml and Cargo.lock unmodified,
-# and build the application.
-FROM rust:bullseye AS builder
+# Build image (the specific rust version can also be passed, e.g. "1.82-bookworm")
+ARG RUST_IMAGE_VERSION=bookworm
+FROM rust:${RUST_IMAGE_VERSION} AS builder
+
 ARG PROFILE=release
+ARG CARGO_BUILD_FEATURES
+# The GIT_REVISION environment variable is used during build time inside the rust crates
 ARG GIT_REVISION
 ENV GIT_REVISION=$GIT_REVISION
-WORKDIR "$WORKDIR/iota"
 
-RUN apt-get update && apt-get install -y cmake clang
+WORKDIR "/iota"
 
-COPY Cargo.toml Cargo.lock ./
+# Install build dependencies, including clang and lld for faster linking
+RUN apt update && apt install -y cmake clang lld
+
+# Configure Rust to use clang and lld as the linker
+RUN mkdir -p ~/.cargo && \
+    echo -e "[target.x86_64-unknown-linux-gnu]\nlinker = \"clang\"\nrustflags = [\"-C\", \"link-arg=-fuse-ld=lld\"]" > ~/.cargo/config.toml
+
+# Install additional dependencies
+RUN apt install -y libpq5 libpq-dev ca-certificates
+
+# Copy in all crates, Cargo.toml, and Cargo.lock
 COPY consensus consensus
 COPY crates crates
-COPY iota-execution iota-execution
-COPY external-crates external-crates
 COPY docs docs
+COPY external-crates external-crates
+COPY iota-execution iota-execution
+COPY Cargo.toml Cargo.lock ./
 
-RUN cargo build --profile ${PROFILE} --bin iota-node
+RUN cargo build --profile ${PROFILE} --bin iota-node --features ${CARGO_BUILD_FEATURES:=default}
 
-# Copy the built binary to the working directory depending on the profile, so we can copy it to the runtime image
-RUN mv target/$(if [ $PROFILE = "dev" ]; then echo "debug"; else echo "release";fi)/iota-node ./
+# Copy the built binary to the working directory depending on the output folder of the profile,
+# so we can copy it to the runtime image
+RUN if [ -d target/release ]; then \
+  TARGET_DIR="target/release"; \
+elif [ -d target/debug ]; then \
+  TARGET_DIR="target/debug"; \
+else \
+  echo "Error: No build directory found"; \
+  exit 1; \
+fi && \
+mv $TARGET_DIR/iota-node ./;
 
-# Production Image
-FROM debian:bullseye-slim AS runtime
+# Production image
+FROM debian:bookworm-slim AS runtime
 
-# Use jemalloc as memory allocator
-RUN apt-get update && apt-get install -y libjemalloc-dev ca-certificates curl
+ARG WORKDIR="/iota"
+WORKDIR "$WORKDIR"
+
+# Install runtime dependencies and tools
+RUN apt update && apt install -y libpq5 ca-certificates curl
+
+# Install jemalloc as the default allocator
+RUN apt install -y libjemalloc-dev
 ENV LD_PRELOAD /usr/lib/x86_64-linux-gnu/libjemalloc.so
 
-WORKDIR "$WORKDIR/iota"
-
-# Both bench and release profiles copy from release dir
-COPY --from=builder /iota/iota-node /opt/iota/bin/iota-node
-
-# Support legacy usages of /usr/local/bin/iota-node
 COPY --from=builder /iota/iota-node /usr/local/bin
 
 ARG BUILD_DATE
diff --git a/docker/iota-tools/Dockerfile b/docker/iota-tools/Dockerfile
--- a/docker/iota-tools/Dockerfile
+++ b/docker/iota-tools/Dockerfile
@@ -1,51 +1,86 @@
-# Build application
-#
-# Copy in all crates, Cargo.toml and Cargo.lock unmodified,
-# and build the application.
-FROM rust:bullseye AS builder
+# Build image (the specific rust version can also be passed, e.g. "1.82-bookworm")
+ARG RUST_IMAGE_VERSION=bookworm
+FROM rust:${RUST_IMAGE_VERSION} AS builder
+
 ARG PROFILE=release
+ARG CARGO_BUILD_FEATURES
+# The GIT_REVISION environment variable is used during build time inside the rust crates
 ARG GIT_REVISION
 ENV GIT_REVISION=$GIT_REVISION
-WORKDIR "$WORKDIR/iota"
 
-RUN apt-get update && apt-get install -y cmake clang libpq5 libpq-dev
+WORKDIR "/iota"
 
-COPY Cargo.toml Cargo.lock ./
+# Install build dependencies, including clang and lld for faster linking
+RUN apt update && apt install -y cmake clang lld
+
+# Configure Rust to use clang and lld as the linker
+RUN mkdir -p ~/.cargo && \
+    echo -e "[target.x86_64-unknown-linux-gnu]\nlinker = \"clang\"\nrustflags = [\"-C\", \"link-arg=-fuse-ld=lld\"]" > ~/.cargo/config.toml
+
+# Install additional dependencies
+RUN apt install -y libpq5 libpq-dev ca-certificates
+
+# Copy in all crates, Cargo.toml, and Cargo.lock
 COPY consensus consensus
 COPY crates crates
-COPY iota-execution iota-execution
-COPY external-crates external-crates
 COPY docs docs
+COPY external-crates external-crates
+COPY iota-execution iota-execution
+COPY Cargo.toml Cargo.lock ./
 
 RUN cargo build --profile ${PROFILE} \
-    --bin iota-node \
-    --bin stress \
-    --bin iota-bridge \
-    --bin bridge-indexer \
-    --bin iota-bridge-cli \
-    --bin iota-analytics-indexer \
-    --bin iota \
-    --bin iota-faucet \
-    --bin iota-cluster-test \
-    --bin iota-tool
+  --bin iota-node \
+  --bin stress \
+  --bin iota-bridge \
+  --bin bridge-indexer \
+  --bin iota-bridge-cli \
+  --bin iota-analytics-indexer \
+  --bin iota \
+  --bin iota-faucet \
+  --bin iota-cluster-test \
+  --bin iota-tool \
+  --features ${CARGO_BUILD_FEATURES:=default}
 
-# Production Image
-FROM debian:bullseye-slim AS runtime
-WORKDIR "$WORKDIR/iota"
+# Copy the built binary to the working directory depending on the output folder of the profile,
+# so we can copy it to the runtime image
+RUN if [ -d target/release ]; then \
+  TARGET_DIR="target/release"; \
+elif [ -d target/debug ]; then \
+  TARGET_DIR="target/debug"; \
+else \
+  echo "Error: No build directory found"; \
+  exit 1; \
+fi && \
+mv $TARGET_DIR/iota-node ./ && \
+mv $TARGET_DIR/stress ./ && \
+mv $TARGET_DIR/iota-bridge ./ && \
+mv $TARGET_DIR/bridge-indexer ./ && \
+mv $TARGET_DIR/iota-bridge-cli ./ && \
+mv $TARGET_DIR/iota-analytics-indexer ./ && \
+mv $TARGET_DIR/iota ./ && \
+mv $TARGET_DIR/iota-faucet ./ && \
+mv $TARGET_DIR/iota-cluster-test ./ && \
+mv $TARGET_DIR/iota-tool ./;
 
-# iota-tool needs libpq at runtime
-RUN apt-get update && apt-get install -y libpq5 libpq-dev ca-certificates
+# Production image
+FROM debian:bookworm-slim AS runtime
 
-COPY --from=builder /iota/target/release/iota-node /usr/local/bin
-COPY --from=builder /iota/target/release/stress /usr/local/bin
-COPY --from=builder /iota/target/release/iota-bridge /usr/local/bin
-COPY --from=builder /iota/target/release/bridge-indexer /usr/local/bin
-COPY --from=builder /iota/target/release/iota-bridge-cli /usr/local/bin
-COPY --from=builder /iota/target/release/iota-analytics-indexer /usr/local/bin
-COPY --from=builder /iota/target/release/iota /usr/local/bin
-COPY --from=builder /iota/target/release/iota-faucet /usr/local/bin
-COPY --from=builder /iota/target/release/iota-cluster-test /usr/local/bin
-COPY --from=builder /iota/target/release/iota-tool /usr/local/bin
+ARG WORKDIR="/iota"
+WORKDIR "$WORKDIR"
+
+# Install runtime dependencies and tools
+RUN apt update && apt install -y libpq5 ca-certificates curl
+
+COPY --from=builder /iota/iota-node /usr/local/bin
+COPY --from=builder /iota/stress /usr/local/bin
+COPY --from=builder /iota/iota-bridge /usr/local/bin
+COPY --from=builder /iota/bridge-indexer /usr/local/bin
+COPY --from=builder /iota/iota-bridge-cli /usr/local/bin
+COPY --from=builder /iota/iota-analytics-indexer /usr/local/bin
+COPY --from=builder /iota/iota /usr/local/bin
+COPY --from=builder /iota/iota-faucet /usr/local/bin
+COPY --from=builder /iota/iota-cluster-test /usr/local/bin
+COPY --from=builder /iota/iota-tool /usr/local/bin
 
 ARG BUILD_DATE
 ARG GIT_REVISION
