feat(scripts): add script to sort Cargo.toml dependencies (#3602)
* feat(scripts): add script to sort Cargo.toml dependencies

* feat(workflow): add `cargosort` workflow

* fix(workflow): use correct python command

* feat(scripts): add `--skip-dprint` option

* fix(script): fix getting package name from Cargo.toml

* fix(workflow): manually check the staging area for diffs

* fix(node): format Cargo.toml files

* feat(scripts): add README

* Fix workflow job name

Co-authored-by: Thibault Martinez <thibault@iota.org>

* fix(scripts): address review comments

* fix(workflow): change directory in cargo-sort step

---------

Co-authored-by: Thibault Martinez <thibault@iota.org>

diff --git a/.github/workflows/_rust_lints.yml b/.github/workflows/_rust_lints.yml
--- a/.github/workflows/_rust_lints.yml
+++ b/.github/workflows/_rust_lints.yml
@@ -27,6 +27,24 @@ jobs:
       - name: Check Rust formatting
         run: cargo +nightly ci-fmt
 
+  cargo-sort:
+    if: (!cancelled() && inputs.isRust)
+    runs-on: [self-hosted]
+    steps:
+      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # pin@v4
+      - name: Check Cargo.toml format and sorting
+        run: |
+          pushd "scripts/cargo_sort"
+          ./run.sh --skip-dprint
+          popd
+      - name: Check Cargo.toml diffs after formatting
+        run: |
+          if git status --porcelain | grep -q "Cargo.toml"; then
+            echo "Cargo.toml files not formatted and/or sorted properly! Please run the 'scripts/cargo_sort/run.sh' script."
+            git diff  # Show the actual diffs
+            exit 1    # Fail the workflow
+          fi
+
   clippy:
     if: (!cancelled() && !failure() && inputs.isRust)
     needs:
