nightly advanced infos

diff --git a/.github/workflows/cargo_llvm_cov.yml b/.github/workflows/cargo_llvm_cov.yml
--- a/.github/workflows/cargo_llvm_cov.yml
+++ b/.github/workflows/cargo_llvm_cov.yml
@@ -46,7 +46,8 @@ jobs:
 
       - name: Install llvm-tools
         run: |
-          TOOLCHAIN=$(rustup show active-toolchain | cut -d ' ' -f 1)
+          # TOOLCHAIN=$(rustup show active-toolchain | cut -d ' ' -f 1)
+          TOOLCHAIN=nightly
           rustup component add llvm-tools --toolchain "$TOOLCHAIN"
           LLVM_PROFDATA=$HOME/.rustup/toolchains/$TOOLCHAIN/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-profdata
           echo "LLVM_PROFDATA=$LLVM_PROFDATA" >> $GITHUB_ENV
@@ -58,13 +59,14 @@ jobs:
             exit 1
           fi
 
-      - name: Compute code coverage and create report (nextest.info)
+      - name: Compute code coverage (nextest.profdata)
         run: |
-          cargo llvm-cov clean --profraw-only
+          cargo +nightly llvm-cov clean --profraw-only
 
           echo "Computing nextest code coverage."
           set +e
-          IOTA_SKIP_SIMTESTS=1 cargo llvm-cov \
+          IOTA_SKIP_SIMTESTS=1 cargo +nightly llvm-cov \
+            --branch \
             --ignore-run-fail \
             --no-report \
             nextest -vv
@@ -80,25 +82,26 @@ jobs:
           find target/llvm-cov-target -name '*.profraw' -print0 | xargs -0 $LLVM_PROFDATA merge --failure-mode=warn --sparse --output target/nextest.profdata
           [ -f "target/nextest.profdata" ] || exit 1
 
-      # - name: Compute code coverage and create report (simtest.info)
+      # - name: Compute code coverage (simtest.profdata)
       #   run: |
-      #     cargo llvm-cov clean --profraw-only
+      #     cargo +nightly llvm-cov clean --profraw-only
+
       #     git clean -fd
       #     set +e
       #     ./scripts/simtest/simtest-cov.sh
       #     # For now we accept failing simtest coverage
-      #     # [ -f "target/simtest.info" ] || exit 1
-      #     if [ ! -f "target/simtest.info" ]; then
-      #       echo "Error: failed to create simtest report."
+      #     # [ -f "target/simtest.profdata" ] || exit 1
+      #     if [ ! -f "target/simtest.profdata" ]; then
+      #       echo "Error: failed to create simtest.profdata."
       #     fi
       #     exit 0
 
       - name: Create html report (report.tgz)
         run: |
-          cd target || exit 1
+          cd target
 
           if [ -d "report" ]; then
-            echo "Cleaning up."
+            echo "Cleaning old report."
             rm -rf report
           fi
 
@@ -106,13 +109,21 @@ jobs:
           if [ -f "simtest.profdata" ]; then
             $LLVM_PROFDATA merge --failure-mode=warn --sparse nextest.profdata simtest.profdata --output merged.profdata
           else
-            $LLVM_PROFDATA merge --failure-mode=warn --sparse nextest.profdata --output merged.profdata
+            mv nextest.profdata merged.profdata
           fi
+
           [ -f "merged.profdata" ] || exit 1
-          LLVM_PROFILE_FILE="merged.profdata" cargo llvm-cov report \
+
+          LLVM_PROFILE_FILE="merged.profdata" cargo +nightly llvm-cov report \
             --html \
-            --output-dir report \
+            --show-instantiations \
+            --show-missing-lines \
+            --doctests \
+            --output-dir . \
             --ignore-filename-regex 'external-crates/.*'
+
+          [ -d "html" ] || exit 1
+          mv html report
 
           echo "Packaging html report."
           [ -d "report" ] || exit 1
