clean up the mess

diff --git a/.github/workflows/cargo_llvm_cov.yml b/.github/workflows/cargo_llvm_cov.yml
--- a/.github/workflows/cargo_llvm_cov.yml
+++ b/.github/workflows/cargo_llvm_cov.yml
@@ -54,31 +54,33 @@ jobs:
       - name: Update Rust toolchain
         run: rustup update stable
 
-      # - name: Generate code coverage
-      #   run: |
-      #     cargo llvm-cov clean
-      #     IOTA_SKIP_SIMTESTS=1 cargo +nightly llvm-cov --ignore-run-fail --branch --html nextest -vv
+      - name: Generate code coverage
+        run: |
+          cargo llvm-cov clean
+          set +e
+          IOTA_SKIP_SIMTESTS=1 cargo +nightly llvm-cov --ignore-run-fail --branch --html nextest
+          if [ -d "target/llvm-cov/html" ]; then
+            exit 0
+          else
+            echo "Fatal Error: Failed to create coverage report."
+            exit 1
+          fi
 
-      # - name: Pack report
-      #   if: always()
-      #   run: |
-      #     if [ ! -d "target/llvm-cov/html" ]; then
-      #       echo "Error: No coverage report created in previous step."
-      #       exit 1
-      #     fi
-      #     cd target/llvm-cov/html && tar -czvf ../nextest_coverage_report.tgz ./
+      - name: Pack report
+        run: cd target/llvm-cov/html && tar -czvf ../nextest_coverage_report.tgz ./
 
-      # - name: Upload report
-      #   uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # pin@v4
-      #   with:
-      #     name: nextest_coverage_report.tgz
-      #     path: ./target/llvm-cov/nextest_coverage_report.tgz
-      #     if-no-files-found: error
-      #     retention-days: 1
+      - name: Upload report
+        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # pin@v4
+        with:
+          name: nextest_coverage_report.tgz
+          path: ./target/llvm-cov/nextest_coverage_report.tgz
+          if-no-files-found: error
+          retention-days: 1
 
       - name: Generate code coverage (simtest)
         run: |
           git clean -fd
+          cargo llvm-cov clean
           set +e
           ./scripts/simtest/codecov.sh
           if [ -d "target/llvm-cov/html" ]; then
