refactor

diff --git a/.github/workflows/cargo_llvm_cov.yml b/.github/workflows/cargo_llvm_cov.yml
--- a/.github/workflows/cargo_llvm_cov.yml
+++ b/.github/workflows/cargo_llvm_cov.yml
@@ -19,7 +19,7 @@ jobs:
       CARGO_TERM_COLOR: always
       CARGO_INCREMENTAL: 0
       # Find a good balance between runtime performance and accurate code coverage analysis.
-      CARGO_PROFILE_TEST_OPT_LEVEL: 0
+      CARGO_PROFILE_TEST_OPT_LEVEL: 1
       CARGO_PROFILE_TEST_DEBUG: true
       CARGO_PROFILE_TEST_DEBUG_ASSERTIONS: true
       CARGO_PROFILE_TEST_OVERFLOW_CHECKS: false
@@ -44,19 +44,22 @@ jobs:
         with:
           size: 256G
 
-      - name: Compute code coverage and create report (nextest.info)
+      - name: Install llvm-tools
         run: |
-          cargo llvm-cov clean --profraw-only
-
           TOOLCHAIN=$(rustup show active-toolchain | cut -d ' ' -f 1)
           rustup component add llvm-tools --toolchain "$TOOLCHAIN"
-          LLVM_PROFDATA="$HOME/.rustup/toolchains/$TOOLCHAIN/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-profdata"
+          echo "LLVM_PROFDATA=$HOME/.rustup/toolchains/$TOOLCHAIN/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-profdata" >> $GITHUB_ENV
+
           if [ -x "$LLVM_PROFDATA" ]; then
             $LLVM_PROFDATA --version
           else
-            echo "Error: llvm-profdata not found or not executable at $LLVM_PROFDATA"
+            echo "Error: llvm-profdata not found at $LLVM_PROFDATA or not executable."
             exit 1
           fi
+
+      - name: Compute code coverage and create report (nextest.info)
+        run: |
+          cargo llvm-cov clean --profraw-only
 
           echo "Computing nextest code coverage."
           set +e
@@ -65,52 +68,55 @@ jobs:
             --no-report \
             nextest -vv
 
-          echo "Scanning for corrupted .profraw files. This might take a while."
-          find target/llvm-cov-target -name '*.profraw' | while read file; do
-            if ! "$LLVM_PROFDATA" show "$file" > /dev/null 2>&1; then
-                echo "Removing corrupted file: $file"
-                rm "$file"
-            fi
-          done
+          # echo "Scanning for corrupted .profraw files. This might take a while."
+          # find target/llvm-cov-target -name '*.profraw' | while read file; do
+          #   if ! "$LLVM_PROFDATA" show "$file" > /dev/null 2>&1; then
+          #       echo "Removing corrupted file: $file"
+          #       rm "$file"
+          #   fi
+          # done
 
-          echo "Creating nextest report."
-          cargo llvm-cov report \
-            --lcov \
-            --output-path target/nextest.info \
-            --ignore-filename-regex 'external-crates/.*'
+          $LLVM_PROFDATA merge --failure-mode=warn --sparse target/llvm-cov-target/*.profraw -o nextest.profdata
+          [ -f "target/nextest.profdata" ] || exit 1
 
-          [ -f "target/nextest.info" ] || exit 1
-
-      - name: Compute code coverage and create report (simtest.info)
-        run: |
-          cargo llvm-cov clean --profraw-only
-          git clean -fd
-          set +e
-          ./scripts/simtest/simtest-cov.sh
-          # For now we accept failing simtest coverage
-          # [ -f "target/simtest.info" ] || exit 1
-          if [ ! -f "target/simtest.info" ]; then
-            echo "Error: failed to create simtest report."
-          fi
-          exit 0
+      # - name: Compute code coverage and create report (simtest.info)
+      #   run: |
+      #     cargo llvm-cov clean --profraw-only
+      #     git clean -fd
+      #     set +e
+      #     ./scripts/simtest/simtest-cov.sh
+      #     # For now we accept failing simtest coverage
+      #     # [ -f "target/simtest.info" ] || exit 1
+      #     if [ ! -f "target/simtest.info" ]; then
+      #       echo "Error: failed to create simtest report."
+      #     fi
+      #     exit 0
 
       - name: Create html report (report.tgz)
         run: |
-          if ! command -v lcov &> /dev/null; then 
-            sudo apt-get install -y lcov 
-          fi
           cd target || exit 1
+
           if [ -d "report" ]; then
+            echo "Cleaning up."
             rm -rf report
           fi
+
           echo "Creating html report."
-          if [ -f "simtest.info" ]; then
-            genhtml -o report nextest.info simtest.info
+          if [ -f "simtest.profdata" ]; then
+            $LLVM_PROFDATA merge --failure-mode=warn --sparse llvm-cov-target/nextest.profdata llvm-cov/target/simtest.profdata -o merged.profdata
           else
-            genhtml -o report nextest.info
+            $LLVM_PROFDATA merge --failure-mode=warn --sparse llvm-cov-target/nextest.profdata -o merged.profdata
           fi
-          [ -d "report" ] || exit 1
+
+          echo "Creating html report."
+          [ -f "merged.profdata" ] || exit 1
+          LLVM_PROFILE_FILE="merged.profdata" cargo llvm-cov report \
+            --html \
+            --output-dir report \
+            --ignore-filename-regex 'external-crates/.*'
+
           echo "Packaging html report."
+          [ -d "report" ] || exit 1
           tar -czf report.tgz report
           [ -f "report.tgz" ] || exit 1
 
