re-enable nextest

diff --git a/.github/workflows/cargo_llvm_cov.yml b/.github/workflows/cargo_llvm_cov.yml
--- a/.github/workflows/cargo_llvm_cov.yml
+++ b/.github/workflows/cargo_llvm_cov.yml
@@ -44,43 +44,42 @@ jobs:
         with:
           size: 256G
 
-      # - name: Compute code coverage and create report (nextest.info)
-      #   run: |
-      #     cargo llvm-cov clean --profraw-only
+      - name: Compute code coverage and create report (nextest.info)
+        run: |
+          cargo llvm-cov clean --profraw-only
 
-      #     TOOLCHAIN=$(rustup show active-toolchain | cut -d ' ' -f 1)
-      #     rustup component add llvm-tools --toolchain "$TOOLCHAIN"
-      #     LLVM_PROFDATA="$HOME/.rustup/toolchains/$TOOLCHAIN/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-profdata"
-      #     if [ -x "$LLVM_PROFDATA" ]; then
-      #       $LLVM_PROFDATA --version
-      #     else
-      #       echo "Error: llvm-profdata not found or not executable at $LLVM_PROFDATA"
-      #       exit 1
-      #     fi
+          TOOLCHAIN=$(rustup show active-toolchain | cut -d ' ' -f 1)
+          rustup component add llvm-tools --toolchain "$TOOLCHAIN"
+          LLVM_PROFDATA="$HOME/.rustup/toolchains/$TOOLCHAIN/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-profdata"
+          if [ -x "$LLVM_PROFDATA" ]; then
+            $LLVM_PROFDATA --version
+          else
+            echo "Error: llvm-profdata not found or not executable at $LLVM_PROFDATA"
+            exit 1
+          fi
 
-      #     echo "Computing nextest code coverage."
-      #     set +e
-      #     IOTA_SKIP_SIMTESTS=1 cargo llvm-cov \
-      #       --workspace \
-      #       --ignore-run-fail \
-      #       --no-report \
-      #       nextest -vv
+          echo "Computing nextest code coverage."
+          set +e
+          IOTA_SKIP_SIMTESTS=1 cargo llvm-cov \
+            --ignore-run-fail \
+            --no-report \
+            nextest -vv
 
-      #     echo "Scanning for corrupted .profraw files. This might take a while."
-      #     find target/llvm-cov-target -name '*.profraw' | while read file; do
-      #       if ! "$LLVM_PROFDATA" show "$file" > /dev/null 2>&1; then
-      #           echo "Removing corrupted file: $file"
-      #           rm "$file"
-      #       fi
-      #     done
+          echo "Scanning for corrupted .profraw files. This might take a while."
+          find target/llvm-cov-target -name '*.profraw' | while read file; do
+            if ! "$LLVM_PROFDATA" show "$file" > /dev/null 2>&1; then
+                echo "Removing corrupted file: $file"
+                rm "$file"
+            fi
+          done
 
-      #     echo "Creating nextest report."
-      #     cargo llvm-cov report \
-      #       --lcov \
-      #       --output-path target/nextest.info \
-      #       --ignore-filename-regex 'external-crates/.*'
+          echo "Creating nextest report."
+          cargo llvm-cov report \
+            --lcov \
+            --output-path target/nextest.info \
+            --ignore-filename-regex 'external-crates/.*'
 
-      #     [ -f "target/nextest.info" ] || exit 1
+          [ -f "target/nextest.info" ] || exit 1
 
       - name: Compute code coverage and create report (simtest.info)
         run: |
@@ -90,6 +89,9 @@ jobs:
           ./scripts/simtest/simtest-cov.sh
           # For now we accept failing simtest coverage
           # [ -f "target/simtest.info" ] || exit 1
+          if [ ! -f "target/simtest.info" ]; then
+            echo "Error: failed to create simtest report."
+          fi
           exit 0
 
       - name: Create html report (report.tgz)
@@ -103,11 +105,9 @@ jobs:
           fi
           echo "Creating html report."
           if [ -f "simtest.info" ]; then
-            # genhtml -o report nextest.info simtest.info
-            genhtml -o report simtest.info
+            genhtml -o report nextest.info simtest.info
           else
-            # genhtml -o report nextest.info
-            exit 1
+            genhtml -o report nextest.info
           fi
           [ -d "report" ] || exit 1
           echo "Packaging html report."
