check llvm-profdata version

diff --git a/.github/workflows/cargo_llvm_cov.yml b/.github/workflows/cargo_llvm_cov.yml
--- a/.github/workflows/cargo_llvm_cov.yml
+++ b/.github/workflows/cargo_llvm_cov.yml
@@ -40,7 +40,6 @@ jobs:
       # can be removed when actions are available on the image already
       - name: Update Rust toolchain
         run: rustup update stable
-
       - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # pin@v4
       - uses: bmwill/rust-cache@fb63fcd7a959767755b88b5af2f5cbf65fb8a127 # pin@v1
 
@@ -58,10 +57,17 @@ jobs:
       - name: Generate code coverage report (nextest.info)
         run: |
           cargo llvm-cov clean
+          LLVM_PROFDATA="$HOME/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-profdata"
+          if [[ -x "$LLVM_PROFDATA" ]]; then
+            $LLVM_PROFDATA --version
+          else
+            echo "Error: llvm-profdata not found or not executable at $LLVM_PROFDATA"
+            exit 1
+          fi
           set +e
           IOTA_SKIP_SIMTESTS=1 cargo llvm-cov --ignore-run-fail --no-report nextest -vv
           find target/llvm-cov-target -name '*.profraw' | while read file; do
-            if ! "$HOME/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-profdata" show "$file" > /dev/null 2>&1; then
+            if ! $LLVM_PROFDATA show "$file" > /dev/null 2>&1; then
                 echo "Removing corrupted file: $file"
                 rm "$file"
             fi
