fix: renamed code

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,17 +1,17 @@
-name: Attach Sui binaries to a release
+name: Attach Iota binaries to a release
 
 on:
   release:
     types: [ published ]
   workflow_dispatch:
     inputs:
-      sui_tag:
-        description: 'Sui repo tag to build from'
+      iota_tag:
+        description: 'Iota repo tag to build from'
         type: string
         required: true
 
 env:
-  TAG_NAME: "${{ github.event.inputs.sui_tag || github.ref }}"
+  TAG_NAME: "${{ github.event.inputs.iota_tag || github.ref }}"
   BINARY_LIST_FILE: "./binary-build-list.json"
   CARGO_TERM_COLOR: always
   # Disable incremental compilation.
@@ -54,16 +54,16 @@ jobs:
       - name: Clean up and validate ${{ env.TAG_NAME }} tag name
         shell: bash
         run: |
-          export sui_tag=$(echo ${{ env.TAG_NAME }} | sed s/'refs\/tags\/'//)
-          [[ "${sui_tag}" == "main" ]] && echo "tag cannot be equals to 'main'" && exit 1
-          echo "sui_tag=${sui_tag}" >> $GITHUB_ENV
-          export sui_version=$(echo ${sui_tag} | sed -e 's/mainnet-v//' -e 's/testnet-v//')
-          echo "sui_version=${sui_version}" >> $GITHUB_ENV
+          export iota_tag=$(echo ${{ env.TAG_NAME }} | sed s/'refs\/tags\/'//)
+          [[ "${iota_tag}" == "main" ]] && echo "tag cannot be equals to 'main'" && exit 1
+          echo "iota_tag=${iota_tag}" >> $GITHUB_ENV
+          export iota_version=$(echo ${iota_tag} | sed -e 's/mainnet-v//' -e 's/testnet-v//')
+          echo "iota_version=${iota_version}" >> $GITHUB_ENV
 
-      - name: Check out ${{ env.sui_tag }}
+      - name: Check out ${{ env.iota_tag }}
         uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # pin@v3
         with:
-          ref: ${{ env.sui_tag }}          
+          ref: ${{ env.iota_tag }}          
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # pin v4.0.2
@@ -94,15 +94,15 @@ jobs:
         continue-on-error: true
         shell: bash
         run: |
-          echo "s3_archive_exist=$(curl -Is https://sui-releases.s3.us-east-1.amazonaws.com/releases/sui-${{ env.sui_tag }}-${{ env.os_type }}.tgz | head -n 1 | grep '200 OK')" >> $GITHUB_ENV
+          echo "s3_archive_exist=$(curl -Is https://iota-releases.s3.us-east-1.amazonaws.com/releases/iota-${{ env.iota_tag }}-${{ env.os_type }}.tgz | head -n 1 | grep '200 OK')" >> $GITHUB_ENV
 
       - name: Download archive, if it exists
         if: ${{ env.s3_archive_exist != '' }}
         shell: bash
         run: |
           mkdir -p ${{ env.TMP_BUILD_DIR }}
-          aws s3 cp s3://sui-releases/releases/sui-${{ env.sui_tag }}-${os_type}.tgz ./tmp/sui-${{ env.sui_tag }}-${os_type}.tgz
-          tar -xf ./tmp/sui-${{ env.sui_tag }}-${os_type}.tgz -C ${{ env.TMP_BUILD_DIR }}
+          aws s3 cp s3://iota-releases/releases/iota-${{ env.iota_tag }}-${os_type}.tgz ./tmp/iota-${{ env.iota_tag }}-${os_type}.tgz
+          tar -xf ./tmp/iota-${{ env.iota_tag }}-${os_type}.tgz -C ${{ env.TMP_BUILD_DIR }}
 
       - name: Setup caching
         if: ${{ env.s3_archive_exist == '' }}
@@ -138,8 +138,8 @@ jobs:
         if: ${{ env.s3_archive_exist == '' }}
         shell: bash
         run: |
-          [ -f ~/.cargo/env ] && source ~/.cargo/env ; cargo build --bin sui --release --features indexer && mv target/release/sui target/release/sui-pg
-          [ -f ~/.cargo/env ] && source ~/.cargo/env ; cargo build --release && cargo build --profile=dev --bin sui
+          [ -f ~/.cargo/env ] && source ~/.cargo/env ; cargo build --bin iota --release --features indexer && mv target/release/iota target/release/iota-pg
+          [ -f ~/.cargo/env ] && source ~/.cargo/env ; cargo build --release && cargo build --profile=dev --bin iota
 
       - name: Rename binaries for ${{ matrix.os }}
         if: ${{ env.s3_archive_exist == '' }}
@@ -153,67 +153,67 @@ jobs:
             mv ./target/release/${binary}${{ env.extention }} ${{ env.TMP_BUILD_DIR }}/${binary}${{ env.extention }}
           done
 
-          # sui-pg is a special binary that is built with the indexer feature for sui start cmd
-          export binary=$(echo "sui-pg" | tr -d $'\r')
+          # iota-pg is a special binary that is built with the indexer feature for iota start cmd
+          export binary=$(echo "iota-pg" | tr -d $'\r')
           mv ./target/release/${binary}${{ env.extention }} ${{ env.TMP_BUILD_DIR }}/${binary}${{ env.extention }}
 
-          mv ./target/debug/sui${{ env.extention }} ${{ env.TMP_BUILD_DIR }}/sui-debug${{ env.extention }}
-          tar -cvzf ./tmp/sui-${{ env.sui_tag }}-${{ env.os_type }}.tgz -C ${{ env.TMP_BUILD_DIR }} .
-          [[ ${{ env.sui_tag }} == *"testnet"* ]] && aws s3 cp ./tmp/sui-${{ env.sui_tag }}-${{ env.os_type }}.tgz s3://sui-releases/releases/sui-${{ env.sui_tag }}-${{ env.os_type }}.tgz || true
+          mv ./target/debug/iota${{ env.extention }} ${{ env.TMP_BUILD_DIR }}/iota-debug${{ env.extention }}
+          tar -cvzf ./tmp/iota-${{ env.iota_tag }}-${{ env.os_type }}.tgz -C ${{ env.TMP_BUILD_DIR }} .
+          [[ ${{ env.iota_tag }} == *"testnet"* ]] && aws s3 cp ./tmp/iota-${{ env.iota_tag }}-${{ env.os_type }}.tgz s3://iota-releases/releases/iota-${{ env.iota_tag }}-${{ env.os_type }}.tgz || true
 
-      - name: Publish Windows sui binary to Chocolatey
-        if: ${{ matrix.os == 'windows-ghcloud' && contains(env.sui_tag, 'testnet') }}
+      - name: Publish Windows iota binary to Chocolatey
+        if: ${{ matrix.os == 'windows-ghcloud' && contains(env.iota_tag, 'testnet') }}
         shell: bash
         run: |
           choco install checksum
-          export sui_sha=$(checksum -t sha256 ${{ env.TMP_BUILD_DIR }}/sui.exe)
+          export iota_sha=$(checksum -t sha256 ${{ env.TMP_BUILD_DIR }}/iota.exe)
           cd chocolatey
 
           cat <<EOF >>VERIFICATION.txt
-          Sui Binary verification steps
-          1. Download https://github.com/MystenLabs/sui/releases/download/${{ env.sui_tag }}/sui-${{ env.sui_tag }}-windows-x86_64.tgz
-          2. Extract sui.exe
-          3. Verify binary: checksum.exe -t sha256 sui.exe: ${sui_sha}
+          Iota Binary verification steps
+          1. Download https://github.com/iotaledger/iota/releases/download/${{ env.iota_tag }}/iota-${{ env.iota_tag }}-windows-x86_64.tgz
+          2. Extract iota.exe
+          3. Verify binary: checksum.exe -t sha256 iota.exe: ${iota_sha}
 
-          File 'LICENSE.txt' is obtained from: https://github.com/MystenLabs/sui/blob/main/LICENSE
+          File 'LICENSE.txt' is obtained from: https://github.com/iotaledger/iota/blob/main/LICENSE
           EOF
 
-          choco pack --version ${{ env.sui_version }} configuration=release
+          choco pack --version ${{ env.iota_version }} configuration=release
           choco apikey --api-key ${{ secrets.CHOCO_API_KEY }} --source https://push.chocolatey.org/
-          choco push sui.${{ env.sui_version }}.nupkg --source https://push.chocolatey.org/
+          choco push iota.${{ env.iota_version }}.nupkg --source https://push.chocolatey.org/
 
       - name: Upload release artifacts for ${{ matrix.os }} platform
         uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # pin@v3
         with:
-          name: sui-binaries-${{ matrix.os }}
+          name: iota-binaries-${{ matrix.os }}
           if-no-files-found: error
           path: |
-            ./tmp/sui-${{ env.sui_tag }}-${{ env.os_type }}.tgz
+            ./tmp/iota-${{ env.iota_tag }}-${{ env.os_type }}.tgz
 
-      - name: Attach artifacts to ${{ env.sui_tag }} release in GH
+      - name: Attach artifacts to ${{ env.iota_tag }} release in GH
         uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # pin@v1
         with:
-          tag_name: ${{ env.sui_tag }}
+          tag_name: ${{ env.iota_tag }}
           files: |
-            ./tmp/sui-${{ env.sui_tag }}-${{ env.os_type }}.tgz
+            ./tmp/iota-${{ env.iota_tag }}-${{ env.os_type }}.tgz
 
   update-homebrew-formula:
-    name: Run brew bump-formula-pr for sui on testnet releases
+    name: Run brew bump-formula-pr for iota on testnet releases
     needs: release-build
     runs-on: ubuntu-latest
-    # releasing sui cli on testnet releases because it lags `main` less than mainnet, but is more likely to be stable than devnet
-    if: ${{ contains( inputs.sui_tag, 'testnet') || contains( github.ref, 'testnet') }}
+    # releasing iota cli on testnet releases because it lags `main` less than mainnet, but is more likely to be stable than devnet
+    if: ${{ contains( inputs.iota_tag, 'testnet') || contains( github.ref, 'testnet') }}
     steps:
       - name: Clean up tag name ${{ env.TAG_NAME }}
         shell: bash
         run: |
-          echo "sui_tag=$(echo ${{ env.TAG_NAME }} | sed s/'refs\/tags\/'//)" >> $GITHUB_ENV
+          echo "iota_tag=$(echo ${{ env.TAG_NAME }} | sed s/'refs\/tags\/'//)" >> $GITHUB_ENV
           echo "versionless_tag=$(echo ${{ env.TAG_NAME }} | sed s/'refs\/tags\/'// | sed s/'testnet\-v'//)" >> $GITHUB_ENV
       - uses: mislav/bump-homebrew-formula-action@b3327118b2153c82da63fd9cbf58942146ee99f0 # pin@v3
         with:
-          formula-name: sui
+          formula-name: iota
           create-pullrequest: true
-          tag-name: "${{ env.sui_tag }}"
+          tag-name: "${{ env.iota_tag }}"
           commit-message: |
             {{formulaName}} ${{ env.versionless_tag }}
 
@@ -225,21 +225,21 @@ jobs:
           COMMITTER_TOKEN: ${{ secrets.HOMEBREW_GH_FORMULA_BUMP }}
 
   update-homebrew-tap:
-    name: Update mysten-tap sui.rb file
+    name: Update iota-tap iota.rb file
     needs: release-build
     runs-on: ubuntu-latest
-    if: ${{ contains( inputs.sui_tag, 'testnet') || contains( github.ref, 'testnet') }}
+    if: ${{ contains( inputs.iota_tag, 'testnet') || contains( github.ref, 'testnet') }}
     steps:
       - name: Clean up tag name ${{ env.TAG_NAME }}
         shell: bash
         run: |
-          echo "sui_tag=$(echo ${{ env.TAG_NAME }} | sed s/'refs\/tags\/'//)" >> $GITHUB_ENV
+          echo "iota_tag=$(echo ${{ env.TAG_NAME }} | sed s/'refs\/tags\/'//)" >> $GITHUB_ENV
 
-      # Checkout MystenLabs/homebrew-tap
+      # Checkout iotaledger/homebrew-tap
       - name: Checkout Target Repository
         uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # pin@v3
         with:
-          repository: MystenLabs/homebrew-tap
+          repository: iotaledger/homebrew-tap
           # @john's PAT, needs to be rotated jan 5 2025
           token: ${{ secrets.HOMEBREW_TAP_REPO_READ_WRITE }}
           ref: main
@@ -252,9 +252,9 @@ jobs:
       - name: Fetch Ubuntu x86_64 Binary and Compute SHA256
         shell: bash
         run: |
-          echo "sha256_ubuntu_release=$(sha256sum sui-binaries-ubuntu-ghcloud/sui-${{ env.sui_tag }}-ubuntu-x86_64.tgz | awk '{print $1}')" >> $GITHUB_ENV
-          echo "sha256_macos_x86_release=$(sha256sum sui-binaries-macos-latest-xl/sui-${{ env.sui_tag }}-macos-x86_64.tgz  | awk '{print $1}')" >> $GITHUB_ENV
-          echo "sha256_macos_arm_release=$(sha256sum sui-binaries-macos-latest-xlarge/sui-${{ env.sui_tag }}-macos-arm64.tgz | awk '{print $1}' )" >> $GITHUB_ENV
+          echo "sha256_ubuntu_release=$(sha256sum iota-binaries-ubuntu-ghcloud/iota-${{ env.iota_tag }}-ubuntu-x86_64.tgz | awk '{print $1}')" >> $GITHUB_ENV
+          echo "sha256_macos_x86_release=$(sha256sum iota-binaries-macos-latest-xl/iota-${{ env.iota_tag }}-macos-x86_64.tgz  | awk '{print $1}')" >> $GITHUB_ENV
+          echo "sha256_macos_arm_release=$(sha256sum iota-binaries-macos-latest-xlarge/iota-${{ env.iota_tag }}-macos-arm64.tgz | awk '{print $1}' )" >> $GITHUB_ENV
 
       # Install Jinja2 for templating
       - name: Install Jinja2
@@ -269,9 +269,9 @@ jobs:
           # Load the template
           template_loader = jinja2.FileSystemLoader(searchpath="./template")
           template_env = jinja2.Environment(loader=template_loader)
-          template = template_env.get_template("sui.rb.j2")
+          template = template_env.get_template("iota.rb.j2")
 
-          version = "${{ env.sui_tag }}".removeprefix("testnet-v")
+          version = "${{ env.iota_tag }}".removeprefix("testnet-v")
 
           # Render the template with variables
           output = template.render(
@@ -282,7 +282,7 @@ jobs:
           )
 
           # Write the output to the formula file
-          with open("Formula/sui.rb", "w") as file:
+          with open("Formula/iota.rb", "w") as file:
             file.write(output)
           EOF
 
@@ -291,22 +291,22 @@ jobs:
         uses: github-actions-x/commit@722d56b8968bf00ced78407bbe2ead81062d8baa # pin@v2.9
         with:
           github-token: ${{ secrets.HOMEBREW_TAP_REPO_READ_WRITE }}
-          commit-message: "Update Homebrew formula for release ${{ env.sui_tag }}"
-          files: Formula/sui.rb
+          commit-message: "Update Homebrew formula for release ${{ env.iota_tag }}"
+          files: Formula/iota.rb
           push-branch: main
           rebase: 'true'
           force-add: 'true'
           name: ${{ github.triggering_actor }}
           email: ${{ github.triggering_actor }}@users.noreply.github.com
 
-  # Tag all sui images with release tag, so that they can be easily found
+  # Tag all iota images with release tag, so that they can be easily found
   tag-docker-hub-images:
     runs-on: ubuntu-latest
     steps:
-      - name: Dispatch Tagging of images in DockerHub, in MystenLabs/sui-operations
+      - name: Dispatch Tagging of images in DockerHub, in iotaledger/iota-operations
         uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # pin@v3.0.0
         with:
-          repository: MystenLabs/sui-operations
+          repository: iotaledger/iota-operations
           token: ${{ secrets.DOCKER_BINARY_BUILDS_DISPATCH }}
           event-type: tag-docker-images
-          client-payload: '{"sui_commit": "${{ github.sha }}", "repo_name": "all", "tag": "${{ env.TAG_NAME }}"}'
+          client-payload: '{"iota_commit": "${{ github.sha }}", "repo_name": "all", "tag": "${{ env.TAG_NAME }}"}'
